### ISSUE TITLE
Pack maker question

### ISSUE THREAD

**Issue by wizard1399** [BuiltBrokenModding/SBM-woodenBucket#11]
I am in the process of updating an old pack I made in 1.7.10.  I saw that most of the other SBM 's got at least an alpha for 1.10.2. Wooden bucket did not, at least not on curseforge. Is this a mistake or are tou skipping straight to 1. 12 for wooden bucket?

**Comment by DarkGuardsman** [comment]
If you click [branches](https://github.com/BuiltBrokenModding/SBM-woodenBucket/branches) there is a version per MC version. However, I have yet to finish the mod's dependency, VE-FluidHandling, in a releasable state per version. Mainly I just need to backport the functional render code for the buckets. Once done I can make a release for wooden buckets as the code didn't change much.

**Comment by wizard1399** [comment]
I know this is a pain, but could you update the curseforge overview page to let everyone know that 1.10.2 is not forgotten and an update is coming. 

I am greatly looking forward to testing it out once you get the backport done.

**Comment by DarkGuardsman** [comment]
:P or i can release it here later today. As I backported the 1.12 to 1.11 and 1.10 yesterday. Fixing the render issues and other problems delaying the release.

**Comment by wizard1399** [comment]
And there was much rejoicing all throughout the land.

**Comment by DarkGuardsman** [comment]
done https://minecraft.curseforge.com/projects/sbm-wooden-buckets/files/2471252
