### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by vico93** [BuiltBrokenModding/SBM-woodenBucket#14]
Using Forge b2503 and changed replaceVanillaBucketModel to true in forge.cfg

Log: https://gist.github.com/vpontin/c598121ecd69c6e01a7e203be31bc9c2

**Comment by DarkGuardsman** [comment]
Seems you might be missing https://minecraft.curseforge.com/projects/ve-fluidhandling which is needed for the mod. Since this is a common issue I'm going to update the description on curse to note its required for the mod.

**Comment by vico93** [comment]
Oh i didnt saw this! Thanks for the tip
