### ISSUE TITLE
1.14.4 Update?

### ISSUE THREAD

**Issue by Wissi** [BuiltBrokenModding/SBM-woodenBucket#18]
We love your work and are interested in starting to test your mods.

Let us know when you have this ported over as well so we may start to include in our modpacks.

Thanks.

**Comment by bl4ckscor3** [comment]
~~It's already updated. Check the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/sbm-wooden-shears/files).~~ Nevermind, I misread the repository name. Sorry.

**Comment by DarkGuardsman** [comment]
Derping out there @bl4ckscor3 

Either way we plan to update the mod but have no ETA
