### ISSUE TITLE
Wooden Bucket Lore

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/SBM-woodenBucket#5]
http://imgur.com/a/S5cE6

Every wooden bucket with fluid except for milk.

**Comment by DarkGuardsman** [comment]
Not sure what you mean, the info looks fine?

**Comment by GreenCafe** [comment]
I just now realised that it is the wrong screenshot, look at this: http://imgur.com/a/wjuVF

**Comment by DarkGuardsman** [comment]
Ya that is a translation bug in other mods
