### ISSUE TITLE
Curse Launcher is pointing to the wrong files for 1.12

### ISSUE THREAD

**Issue by MokahTGS** [BuiltBrokenModding/SBM-woodenBucket#7]
Wrong repo, you wanted this one
https://github.com/BuiltBrokenModding/SBM-woodenBucket

As well you forgot to install the dep VoltzEngine Fluid module
https://minecraft.curseforge.com/projects/ve-fluidhandling/files

For issue now deleted

**Comment by DarkGuardsman** [comment]
Fixed, also I did not delete the issue but closed the tracker on the old repository since its no longer used.
