### ISSUE TITLE
1.12-0.2.0b9 crashes dedicated server Forge 1.12 build 2400

### ISSUE THREAD

**Issue by kreezxil** [BuiltBrokenModding/SBM-woodenBucket#9]
Notes:
     on startup

crash report:
https://gist.github.com/c01f7106c414e4583677d0b4e9599037

fml server latest:
https://gist.github.com/d4214b1786edd6db203f9775bfc8c831

**Comment by DarkGuardsman** [comment]
Make sure to install VE-FluidHandling module.
https://minecraft.curseforge.com/projects/ve-fluidhandling
